### ISSUE TITLE
Start doesn’t work

### ISSUE THREAD

**Issue by Spencerrrrr366** [qconrad/intellistar-emulator#60]
So when i put in my zip i click start and it’s stuck. It doesn’t load. Please help

**Comment by JesseWx2011** [comment]
Looked into the console, I am given two errors:
`intellistar-emulator/:1 Access to fetch at 'https://api.weather.com/v3/location/point?postalKey=10012:US&language=en-US&format=json&apiKey=21d8a80b3d6b444998a80b3d6b1449d3'  from origin 'https://qconrad.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

`Uncaught (in promise) TypeError: Failed to fetch
    at fetchCurrentWeather (WeatherFetching.js:133:3)
    at HTMLButtonElement.submit (Config.js:85:5)`

I am going to make a fork on this project to see if I can fix it.

**Comment by JesseWx2011** [comment]
@qconrad merged the pull request, this issue has now been fixed.
